// This file is part of smuggler. It is subject to the license terms in the COPYRIGHT file found in the top-level directory of this distribution and at https://raw.githubusercontent.com/lemonrock/smuggler/master/COPYRIGHT. No part of smuggler, including this file, may be copied, modified, propagated, or distributed except according to the terms contained in the COPYRIGHT file.
// Copyright © 2021 The developers of smuggler. See the COPYRIGHT file in the top-level directory of this distribution and at https://raw.githubusercontent.com/lemonrock/smuggler/master/COPYRIGHT.


use crate::collections::{ByteOrder, NonNullExt, Byte};
use crate::collections::CanBeUnaligned;
use crate::collections::Index;
use crate::collections::TiffBytes;
use crate::collections::VecExt;
use crate::tiff::image_file_directory::ImageFileDirectories;
use crate::tiff::image_file_directory::ImageFileDirectory;
use crate::tiff::image_file_directory::pointer::ImageFileDirectoryPointer;
use crate::tiff::image_file_directory::tags::UnrecognizedTag;
use crate::tiff::image_file_directory::tags::parsers::{RecursionGuard, TagParserCommon, RawTagValue};
use crate::tiff::image_file_directory::tags::parsers::UnrecognizedTagParser;
use crate::tiff::offset::Offset;
use likely::unlikely;
use memchr::memchr;
use std::alloc::Allocator;
use std::cell::Cell;
use std::cmp::Ordering;
use std::convert::TryInto;
use std::fmt::Debug;
use std::fmt::Formatter;
use std::fmt;
use std::hash::Hash;
use std::hash::Hasher;
use std::marker::PhantomData;
use std::mem::size_of;
use std::mem::transmute;
use std::num::{NonZeroU8, NonZeroUsize};
use std::ptr::NonNull;
use std::ptr::addr_of;
use std::slice::from_raw_parts;
use std::slice::from_raw_parts_mut;
use std::str::FromStr;
use strum::EnumCount;
use strum::IntoEnumIterator;
use super::TagIdentifier;
use super::parsers::SpecificTagParseError;
use super::parsers::TagParseError;
use super::parsers::Version6OrBigTiffUnit;
use swiss_army_knife::byte_swap::Unaligned16;
use swiss_army_knife::byte_swap::Unaligned32;
use swiss_army_knife::byte_swap::Unaligned64;
use swiss_army_knife::byte_swap;
use swiss_army_knife::non_null::new_non_null;
use swiss_army_knife::non_null::new_non_zero_usize;


include!("AsciiStrings.rs");
include!("BitField.rs");
include!("BitFieldInteger.rs");
include!("EnumSignedInteger.rs");
include!("EnumUnsignedInteger.rs");
include!("IntegerNormalizedType.rs");
include!("RationalFraction.rs");
include!("RationalFractionAtor.rs");
include!("SignedEnum.rs");
include!("SignedInteger.rs");
include!("SignedIntegerNormalizedType.rs");
include!("SignedIntegerValue.rs");
include!("TagType.rs");
include!("Unaligned.rs");
include!("Undefined.rs");
include!("UnsignedEnum.rs");
include!("UnsignedInteger.rs");
include!("UnsignedIntegerNormalizedType.rs");
include!("UnsignedIntegerValue.rs");
include!("UnrecognizedTagValue.rs");
